server:
  port: 5050


spring:
  datasource:
    username: root
    password: dy123456
    url: jdbc:mysql://101.43.66.187:3306/my?useAffectedRows=true&useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.dy.entity


logging:
  level:
    com:
      dy:
        mapper: debug